@include('partials.home.header');
<base href="{!! asset("") !!}" xmlns:required>
<main class="container">
    <div id="contenedor" >
        <section class="row">
            <div class="register-box col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <h2 class="text-primary">Completa tus datos para el registro:</h2>
                <div class="register-logo">
                    <img src="imagenes/imagen_formulario.png"  class="img-responsive logos"alt="imagen_formulario" />
                </div>

                <div id="body_registro">


                    <form action="registroSuccess" method="post">

                        <div class="form-group has-feedback col-xs-12 col-sm-10 col-md-10 col-lg-10">
                            <input type="text" class="form-control" placeholder="Nombre" name="name" required>
                            <span class="glyphicon glyphicon-user form-control-feedback"></span>
                        </div>


                        <div class="form-group has-feedback col-xs-12 col-sm-10 col-md-10 col-lg-10">
                            <input type="email" class="form-control" name="email" placeholder="Email" required>
                            <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
                        </div>

                        <div class="form-group has-feedback col-xs-12 col-sm-10 col-md-10 col-lg-10">
                            <input type="password" class="form-control" name="password" placeholder="Contrase�a" required>
                            <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                        </div>

                         <div class="form-group has-feedback col-xs-12 col-sm-10 col-md-10 col-lg-10">
                           <input type="file" name="fotoPerfil"/>
                            <span class="glyphicon glyphicon-picture form-control-feedback"></span>
                         </div>

                        <input type="hidden" name="_token" value="{{csrf_token()}}">
                        <div class="row">
                            <div class="col-xs-8">
                                <div class="checkbox">
                                    <label>
                                        <input type="checkbox" name="terminosYcondiciones" required> Acepto los <a href="#terminos" data-toggle="modal" data-dismiss="modal">terminos y condiciones</a>
                                    </label>
                                </div>
                            </div>

                            <div class="modal fade" id="terminos">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                            <h3 class="modal-title">Terminos y condiciones</h3>
                                        </div>
                                        <div class="modal-body">
                                            <p>Los siguientes t�rminos y condiciones rigen todo el uso de la p�gina web SimpsonsBlog.com y todo el contenido, servicios y productos disponibles en oa trav�s del sitio web (en conjunto, el Sitio Web). El sitio Web es propiedad y est� operado por la Crear Blog (�Crear Blog�). El sitio web se ofrece sujeta a la aceptaci�n sin excepciones de todos los t�rminos y condiciones contenidos en el presente documento y todas las dem�s reglas de operaci�n, pol�ticas (incluyendo, sin limitaci�n, de Crear Blog pol�tica de privacidad) y procedimientos que pueden ser publicados de vez en cuando en este Sitio por Crear Blog (colectivamente, el �Contrato�).
                                                Por favor, lea este Acuerdo cuidadosamente antes de acceder o utilizar el Sitio Web. Al acceder o utilizar cualquier parte del sitio Web, usted acepta quedar obligado por los t�rminos y condiciones de este acuerdo. Si usted no est� de acuerdo con todos los t�rminos y condiciones de este acuerdo, entonces usted no puede tener acceso al sitio Web o utilizar cualquiera de los servicios. Si estos t�rminos y condiciones se consideran una oferta por Crear Blog de la, la aceptaci�n est� expresamente limitada a estos t�rminos. El sitio web est� disponible s�lo para personas que tengan al menos 13 a�os de edad.
                                                Su cuenta SimpsonsBlog.com y del sitio.<br> Si se crea un blog / sitio en la Web, que son responsables de mantener la seguridad de su cuenta y el blog, y usted es completamente responsable de todas las actividades que ocurran bajo la cuenta y otras acciones tomadas en relaci�n con el blog. Usted no debe describir o asignar palabras clave a tu blog de una manera enga�osa o ilegal, incluso en una forma prevista para el comercio en el nombre o la reputaci�n de los dem�s, y Crear Blog puede cambiar o eliminar cualquier descripci�n o palabra clave que considere inapropiado o il�cito , o de lo contrario puede causar Crear un Blog responsabilidad. Usted debe notificar inmediatamente Crear un Blog de cualquier uso no autorizado de su blog, su cuenta o cualquier otra violaci�n de la seguridad. Crear Blog de la no se hace responsable por los actos u omisiones de usted, incluyendo los da�os y perjuicios de cualquier tipo incurridos como resultado de dichos actos u omisiones.
                                                Responsabilidad de contribuyentes. Si usted opera un blog, comentar en un blog, publicar material para el sitio web, publicar enlaces en el Sitio Web, o de lo contrario hacer (o permitir a terceros a hacer) material disponible a trav�s de la p�gina web (dicho material , �Contenido�), Usted es el �nico responsable por el contenido de, y cualquier da�o resultante de, que de contenido. Ese es el caso, independientemente de si el contenido en cuesti�n constituye el texto, gr�ficos, un archivo de audio, o programas inform�ticos. Al hacer contenido disponible, usted representa y garantiza que:
                                                la descarga, copia y uso del Contenido no infringir� los derechos de propiedad, incluyendo pero no limitado a los derechos de autor, patentes, marcas o derechos de secretos comerciales, de cualquier tercero;
                                                si su empleador tiene derecho a la propiedad intelectual se crea, usted tiene ya sea (i) recibi� el permiso de su empleador para enviar o poner a disposici�n el Contenido, incluyendo, pero no limitado a cualquier software, o (ii) asegur� de su empleador una dispensa en cuanto a todos los derechos sobre o en el contenido;
                                                usted ha cumplido plenamente con todas las licencias de terceros en relaci�n con el contenido, y ha hecho todas las cosas necesarias para pasar con �xito a los usuarios finales a trav�s de cualquiera de los t�rminos requeridos;
                                                el contenido no contiene ni instala ning�n virus, gusanos, malware, troyanos u otros contenidos da�inos o destructivos;<br>
                                                el contenido no es spam, no se a m�quina o generada de forma aleatoria, y no contiene contenido comercial no �tica o no deseado dise�ado para dirigir el tr�fico a sitios de terceros o impulsar los rankings en los motores de b�squeda de sitios de terceros, ni a otros actos ilegales (tales como phishing) o enga�ar a los destinatarios como a la fuente de los materiales (como spoofing);
                                                el contenido no es pornogr�fico, no contiene amenazas o inciten a la violencia hacia las personas o entidades, y no viola la privacidad o derechos de publicidad de terceros;
                                                tu blog no est� siendo anunciado v�a mensajes electr�nicos no deseados, tales como enlaces de spam en grupos de noticias, listas de correo electr�nico, blogs y otros sitios web, y los m�todos promocionales no solicitados similares;
                                                tu blog no es el nombre de una manera que induce a error a sus lectores a pensar que eres otra persona o empresa. Por ejemplo, la direcci�n URL o el nombre de su blog no es el nombre de una persona que no sea usted o que no sea su propia empresa; y
                                                que tiene, en el caso de contenido que incluye c�digo de computadora, clasificada por categor�as y / o describe el tipo, naturaleza, usos y efectos de los materiales, ya sea requerido para ello por Crear Blog de la o de otra manera.
                                                <br>Al enviar contenido a Crear Blog de la para la inclusi�n en su sitio web, usted otorga Crear un Blog de una licencia, libre de regal�as y no exclusiva a nivel mundial para reproducir, modificar, adaptar y publicar el contenido con el �nico prop�sito de mostrar, distribuir y la promoci�n de su blog. Si elimina contenido, Crear un Blog utilizar� esfuerzos razonables para eliminarlo de la p�gina web, pero usted reconoce que el almacenamiento en cach� o las referencias al contenido no se pueden hacer inmediatamente disponible.
                                                Sin limitaci�n alguna de esas representaciones o garant�as, Crear Blog tiene el derecho (aunque no la obligaci�n), a la sola discreci�n de Crear Blog (i) rechazar o eliminar cualquier contenido que, a juicio razonable de Crear Blog, viola cualquiera Crear Blog pol�tica o es de ninguna manera perjudicial o censurable, o (ii) terminar o negar el acceso y uso del Sitio Web a cualquier persona o entidad por cualquier raz�n, a la sola discreci�n de Blog Crear un. Crear Blog no tendr� obligaci�n de facilitar la devoluci�n de los importes pagados previamente.
                                                Pago y Renovaci�n.
                                                <br>Condiciones Generales.
                                                Al seleccionar un producto o servicio, usted se compromete a pagar Crear un Blog el tiempo de uno y / o cuotas mensuales o anuales de suscripci�n indicadas (condiciones de pago adicionales pueden incluirse en otras comunicaciones). Pagos de suscripci�n ser�n cargados en una base pre-pago en el d�a usted se inscribe para una actualizaci�n y cubrir� el uso de ese servicio por un periodo de suscripci�n mensual o anual, como se indica. Los pagos no son reembolsables.
                                                Renovaci�n autom�tica.
                                                A menos que usted notifique Crear un Blog antes de que finalice el per�odo de suscripci�n aplicable que desea cancelar una suscripci�n, su suscripci�n se renovar� autom�ticamente y usted nos autoriza a cobrar la cuota de suscripci�n anual o mensual, entonces aplicable para dicha suscripci�n (as� como cualquier impuestos) utilizando cualquier tarjeta de cr�dito u otro mecanismo de pago que tenemos en el expediente para usted. Las actualizaciones se pueden cancelar en cualquier momento mediante la presentaci�n de su solicitud para Crear Blog por escrito.
                                                Servicios.<br>
                                                Honorarios; El pago.<br> Al suscribirse a un paquete de servicios de cuenta usted acepta pagar Crear un Blog el aplicable cuotas de alta y cargos recurrentes. Los honorarios aplicables ser�n facturados a partir del d�a de sus servicios se establecen y con antelaci�n de la utilizaci�n de dichos servicios. Crear Blog se reserva el derecho de modificar los t�rminos y las tarifas de pago a los treinta notificaci�n por escrito (30) d�as antes de usted. Los servicios pueden ser cancelados por usted en cualquier momento en los treinta (30) d�as de aviso por escrito a Crear Blog.
                                                Soporte. Si su servicio incluye acceso a correo electr�nico de apoyo prioridad. �Asistencia por correo electr�nico� significa la capacidad de hacer las solicitudes de asistencia de soporte t�cnico por correo electr�nico en cualquier momento (con un esfuerzo razonable por Crear Blog Naciones Unidas para responder dentro de los 10 d�as h�biles) concerniente al uso de los Servicios VIP. �Prioridad� significa que el apoyo tiene prioridad sobre el apoyo a los usuarios de los servicios SimpsonsBlog.com est�ndar o libres. Todo el apoyo se proporciona de acuerdo con la CREAR blog servicios est�ndar pr�cticas, procedimientos y pol�ticas.
                                                Responsabilidad de los visitantes del Web site. Crear Blog de ??la no ha revisado, y no puede revisar, todo el material, incluidos los programas inform�ticos, publicado en el Sitio Web, y por lo tanto no puede ser responsable por el contenido, uso o efectos de ese material. Al operar el Sitio Web, Crear Blog no representa ni implica que respalda el material no publicado, o que cree que dicho material sea precisa, �til o no nocivo. Usted es responsable de tomar las precauciones necesarias para protegerse y proteger sus sistemas inform�ticos de los virus, gusanos, caballos de Troya y otros contenidos da�inos o destructivos. El Sitio Web puede contener contenido que es ofensivo, indecente u objetable, as� como el contenido que contenga imprecisiones t�cnicas, errores tipogr�ficos y otros errores. El sitio Web tambi�n puede contener material que viole los derechos de privacidad o publicidad, o infrinja la propiedad intelectual y otros derechos de propiedad, de terceros, o la descarga, copia o utilizaci�n de los cuales est� sujeto a t�rminos y condiciones adicionales, que se establezca o no declarada. Crear Blog se exime de cualquier responsabilidad por cualquier da�o resultante del uso por los visitantes del sitio web, o de cualquier descarga por los visitantes del contenido all� publicado.
                                                Contenido publicado en otros sitios web. No hemos revisado, y no puede revisar, todo el material, incluidos los programas inform�ticos, disponibles a trav�s de los sitios web y p�ginas web para que SimpsonsBlog.com enlaces, y que enlace a SimpsonsBlog.com. Crear Blog de la no tiene ning�n control sobre esos sitios web no CREAR blog de la y p�ginas web, y no se hace responsable de su contenido ni su uso. Al vincular a un sitio web no Crear Blog o p�gina web, Crear Blog no representa ni implica que respalda dicho sitio web o p�gina web. Usted es responsable de tomar las precauciones necesarias para protegerse y proteger sus sistemas inform�ticos de los virus, gusanos, caballos de Troya y otros contenidos da�inos o destructivos. Crear Blog se exime de cualquier responsabilidad por cualquier da�o que resulte del uso de la no-CREAR sitios web de las Naciones Unidas de blog y p�ginas web.
                                                Infracci�n de copyright y Pol�tica de DMCA. Como Crear Blog pide a los dem�s a respetar sus derechos de propiedad intelectual, que respeta los derechos de propiedad intelectual de los dem�s. Si usted cree que el material situado en o vinculado a por SimpsonsBlog.com viola sus derechos de autor, se le anima a notificar Crear Blog en conformidad con la Ley de Crear Blog del Milenio Digital de Derechos de Autor (�DMCA�) con la Pol�tica. Crear Blog responder� a todos estos anuncios, incluyendo seg�n sea necesario o apropiado por la eliminaci�n del material infractor o desactivando todos los enlaces a material infractor. Crear Blog cancelar el acceso de un visitante y uso de la p�gina web si, en circunstancias apropiadas, el visitante se determina que es un infractor reincidente de los derechos de autor u otros derechos de propiedad intelectual de Crear Blog de la o de otros. En el caso de dicha terminaci�n, Crear un Blog no tendr� obligaci�n de facilitar la devoluci�n de los importes pagados previamente a Crear Blog.
                                                Propiedad Intelectual. Este Acuerdo no transfiere desde Crear Blog de ??la para que cualquier Blog Crear Naciones Unidas o de un tercero la propiedad intelectual, y todos los derechos, t�tulos e intereses sobre y para dichos bienes seguir� siendo (como entre las partes) �nicamente con Crear Blog. Crear Blog, SimpsonsBlog.com, el logotipo de SimpsonsBlog.com, y todas las dem�s marcas comerciales, marcas de servicio, gr�ficos y logotipos usados ??en relaci�n con SimpsonsBlog.com, o el Sitio Web son marcas comerciales o marcas comerciales registradas de Crear Blog de la o de los licenciantes de Crear blog . Otras marcas comerciales, marcas de servicio, gr�ficos y logotipos usados ??en relaci�n con el Sitio Web pueden ser marcas comerciales de terceros. Su uso del sitio web le otorga ning�n derecho o licencia para reproducir o utilizar cualquier CREAR blog de la o de terceros marcas comerciales de otra manera.
                                                Anuncios. Crear Blog se reserva el derecho de mostrar anuncios en tu blog a menos que usted haya adquirido una cuenta libre de publicidad.
                                                Atribuci�n. Crear Blog se reserva el derecho de mostrar los v�nculos de atribuci�n como �Blog en SimpsonsBlog.com,� tema autor, y la atribuci�n de la fuente en el pie de p�gina del blog o barra de herramientas.
                                                Productos de socios. Por la activaci�n de un producto asociado (por ejemplo, el tema) de uno de nuestros socios, concedes a las condiciones de ese socio de servicio. Usted puede optar por salir de sus t�rminos de servicio en cualquier momento desactivando el producto pareja.
                                                Nombres de dominio. Si se registra un nombre de dominio, uso o transferencia de un nombre de dominio registrado anteriormente, usted reconoce y acepta que el uso del nombre de dominio tambi�n est� sujeto a las pol�ticas de la Corporaci�n de Internet para Nombres y N�meros Asignados (�ICANN�) , incluyendo sus derechos de registro y responsabilidades .
                                                Cambios. Crear Blog se reserva el derecho, a su sola discreci�n, de modificar o reemplazar cualquier parte de este Acuerdo. Es su responsabilidad revisar este Acuerdo peri�dicamente para los cambios. El uso continuado de o acceso al Sitio Web tras la publicaci�n de cualquier cambio a este Acuerdo constituye la aceptaci�n de dichos cambios. Crear Blog puede tambi�n, en el futuro, ofrecer nuevos servicios y / o caracter�sticas a trav�s del sitio web (incluyendo, el lanzamiento de nuevas herramientas y recursos). Estas caracter�sticas y / o servicios nuevos estar�n sujetos a los t�rminos y condiciones de este Acuerdo.
                                                Terminaci�n. Crear Blog podr� dar por terminado su acceso a todo o cualquier parte del Sitio Web en cualquier momento, con o sin causa, con o sin previo aviso, con efecto inmediato. Si desea denunciar el presente Acuerdo o su cuenta SimpsonsBlog.com (si tiene uno), puede simplemente dejar de utilizar el Sitio Web. No obstante lo anterior, si usted tiene una cuenta de servicios de pago, dicha cuenta s�lo puede ser terminado por Crear un Blog si usted incumple materialmente este Contrato y no puede curar tal incumplimiento dentro de los treinta (30) d�as a partir de la notificaci�n de Crear Blog a usted mismo; siempre que, Crear un Blog puede rescindir el sitio web de inmediato como parte de un cierre general de abajo de nuestro servicio. Todas las disposiciones de este Acuerdo que por su naturaleza deber�an sobrevivir terminaci�n, sobrevivir�n la terminaci�n, incluyendo, sin limitaci�n, las disposiciones de propiedad, renuncias de garant�a, indemnizaci�n y limitaciones de responsabilidad.
                                                Renuncia de Garant�as. El sitio web se proporciona �tal cual�. Blog Crear y sus proveedores y licenciantes renuncian a todas las garant�as de ning�n tipo, expresa o impl�cita, incluyendo, sin limitaci�n, las garant�as de comerciabilidad, adecuaci�n a un prop�sito particular y no infracci�n. Ni Crear Blog ni sus proveedores y licenciantes, hace ninguna garant�a de que el sitio web est� libre de errores o que el acceso a la misma ser� continua o ininterrumpida. Usted entiende que usted descarga de, o de otro modo obtener el contenido o servicios a trav�s de, el Sitio Web en su propia discreci�n y riesgo.
                                                Limitaci�n de responsabilidad En ning�n caso ser�n Crear blog de ??la, o sus proveedores o licenciatarios, ser� responsable con respecto a cualquier materia objeto de este acuerdo bajo cualquier contrato, negligencia, responsabilidad estricta o cualquier otra teor�a legal o equitativa para:. (I) cualquier da�o especial , da�os incidentales o consecuentes; (Ii) el costo de la contrataci�n de productos o servicios sustitutivos; (Iii) por interrupci�n del uso o de la p�rdida o corrupci�n de datos; o (iv) para las cantidades que exceden los honorarios pagados por usted para Crear Blog de la en virtud de este acuerdo durante el per�odo de doce (12) meses anteriores a la causa de la acci�n. Crear Blog no tendr� ninguna responsabilidad por cualquier falla o retraso debido a cuestiones ajenas a su control razonable. Lo anterior no se aplicar� en la medida prohibida por la ley aplicable.
                                                Representaci�n general y Garant�a. Usted manifiesta y garantiza que (i) su uso del Sitio Web ser� en estricta conformidad con las Naciones Unidas Pol�tica de Privacidad Blog Crear, con este Acuerdo y con todas las leyes y reglamentos aplicables (incluyendo sin limitaci�n las leyes o reglamentos locales en su pa�s, estado, ciudad, u otra �rea gubernamental, con respecto a la conducta en l�nea y contenido aceptable, e incluyendo todas las leyes aplicables a la transmisi�n de datos t�cnicos exportados desde los Estados Unidos o el pa�s en el que reside) y (ii) su uso del Sitio Web no infringir� o apropiarse indebidamente de los derechos de propiedad intelectual de terceros.
                                                Indemnizaci�n. Usted acepta indemnizar y mantener indemne Blog Crear un, sus contratistas y sus licenciantes, y sus respectivos directores, funcionarios, empleados y agentes de y contra cualquiera y todas las reclamaciones y gastos, incluyendo honorarios de abogados, que surjan de su uso del sitio Web, incluyendo pero no limitado a su violaci�n de este Acuerdo.
                                                Varios. <br>Este Acuerdo constituye el acuerdo completo entre Crear Blog y usted en relaci�n con el objeto del mismo, y que s�lo puede ser modificada por una enmienda escrita firmada por un ejecutivo autorizado de Crear Blog de ??la, o por la publicaci�n por Crear Blog de un versi�n revisada. Salvo en la medida en la ley aplicable, en su caso, disponga otra cosa, este Acuerdo, cualquier acceso o uso del Sitio Web se regir� por las leyes del estado de Illinois, EE.UU., excluyendo su conflicto de disposiciones legales, y el lugar adecuado para cualquier disputa que surja de o en relaci�n con cualquiera de la misma ser�n los tribunales estatales y federales ubicados en el Condado de Cook, Illinois. A excepci�n de las solicitudes de medidas cautelares o de equidad o reclamaciones relativas a los derechos de propiedad intelectual (que pueden introducirse en cualquier tribunal competente, sin el dep�sito de una fianza), cualquier disputa que surja en virtud del presente Acuerdo se resolver�n de conformidad con las Reglas Completas de Arbitraje de la Servicio de Mediaci�n, Inc. (�JAMS�) por tres �rbitros designados de acuerdo con estas Reglas de Arbitraje y Judicial. El arbitraje se llevar� a cabo en Chicago, Illinois, en el idioma Ingl�s y la decisi�n arbitral puede ser ejecutada en cualquier tribunal. La parte que prevalezca en cualquier acci�n o procedimiento para hacer cumplir este Acuerdo tendr� derecho a los costos y honorarios de abogados. Si alguna parte de este Acuerdo es considerada inv�lida o inaplicable, dicha parte se interpretar� en el sentido de reflejar la intenci�n original de las partes, y las partes restantes permanecer�n en pleno vigor y efecto. La renuncia por cualquiera de las partes de cualquier t�rmino o condici�n de este Contrato o cualquier incumplimiento del mismo, en cualquier instancia, no renunciar� a dicho t�rmino o condici�n o cualquier incumplimiento posterior de la misma. Usted puede asignar sus derechos bajo este Acuerdo a cualquier parte que consienta, y se compromete a estar obligado por sus t�rminos y condiciones; Crear Blog podr� ceder sus derechos en virtud del presente Acuerdo y sin condiciones. Este Acuerdo ser� vinculante y redundar� en beneficio de las partes, sus sucesores y cesionarios permitidos.</p>
                                        </div>
                                        <div class="modal-footer">
                                            <button class="btn btn-danger" type="button" data-dismiss="modal">Salir</button>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                                <button type="submit" class="btn btn-primary btn-block btn-flat">Registrarse</button>
                            </div>

                        </div>
                    </form>


                    @if($errors->any())

                        <ol style="color:red">
                            @foreach($errors->all()as $error)
                            <li>{{$error}}</li>
                            @endforeach

                        </ol>

                        @endif
                </div>
        </section>
    </div>
</main>

</div>
@include('partials.home.footer');